
var countryCodes = {
    "Afghanistan":"AF",
    "Albania":"AL",
    "Algeria":"DZ",
    "Andoora":"AD",
    "Angola":"AO",
    "Antigua and Barbuda":"AG",
    "Argentina":"AR",
    "Armenia":"AM",
    "Austrailia":"AU",
    "Austria":"AT",
    "Azerbaijan":"AZ",
    "Bahamas":"BS",
    "Bahrain":"BH",
    "Bangladesh":"BD",
    "Barbados":"BB",
    "Belarus":"BY",
    "Belgium":"BE",
    "Belize":"BZ",
    "Benin":"BJ",
    "Bhutan":"BT",
    "Bolivia":"BO",
    "Bosnia and Herzegovina":"BA",
    "Botswana":"BW",
    "Brazil":"BR",
    "Brunei Darussalam":"BN",
    "Bulgaria":"BG",
    "Burkina Faso":"BF",
    "Burundi":"BI",
    "Cambodia":"KH",
    "Cameroon":"CM",
    "Canada":"CA",
    "Cape Verde":"CV",
    "Central African Republic":"CF",
    "Chad":"TD",
    "Chile":"CL",
    "China":"CN",
    "Colombia":"CO",
    "Comoros":"KM",
    "Congo":"CG",
    "Cook Islands":"CK",
    "Costa Rica":"CR",
    "Cote dIvoire":"CI",
    "Croatia":"HR",
    "Cyprus":"CY",
    "Czech Republic":"CZ",
    "Denmark":"DK",
    "Dijbouti":"DJ",
    "Dominica":"DM",
    "Dominican Republic":"DO",
    "Democratic Republic of the Congo":"CD",
    "Ecuador":"EC",
    "Egypt":"EG",
    "El Salvador":"SV",
    "Egypt":"EG",
    "Equatorial Guinea":"GQ",
    "Eritrea":"ER",
    "Estonia":"EE",
    "Ethiopia":"ET",
    "Fiji":"FJ",
    "Finland":"FI",
    "France":"FR",
    "Gabon":"GA",
    "Gambia":"GM",
    "Georgia":"GE",
    "Germany":"DE",
    "Ghana":"GH",
    "Greece":"GR",
    "Grenada":"GD",
    "Guatemala":"GT",
    "Guinea":"GN",
    "Guinea-Bissau":"GW",
    "Guyana":"GY",
    "Haiti":"HT",
    "Honduras":"HN",
    "Hungary":"HU",
    "Iceland":"IS",
    "India":"IN",
    "Indonesia":"ID",
    "Iran (Islamic Republic of)":"IR",
    "Iraq":"IQ",
    "Ireland":"IE",
    "Israel":"IL",
    "Italy":"IT",
    "Jamaica":"JM",
    "Japan":"JP",
    "Jordan":"JO",
    "Kazakhstan":"KZ",
    "Kenya":"KE",
    "Kiribati":"KI",
    "Kuwait":"KW",
    "Kyrgyzstan":"KG",
    "Lao People's Democratic Republic":"LA",
    "Latvia":"LV",
    "Lebanon":"LB",
    "Lesotho":"LS",
    "Liberia":"LR",
    "Lithuania":"LT",
    "Luxembourg":"LU",
    "Madagascar":"MG",
    "Malawi":"MW",
    "Malaysia":"MY",
    "Maldives":"MV",
    "Mali":"ML",
    "Malta":"MT",
    "Marshall Islands":"MH",
    "Mauritania":"MR",
    "Mauritius":"MU",
    "Mexico":"MX",
    "Micronesia (Federated States of)":"FM",
    "Monaco":"MC",
    "Mongolia":"MN",
    "Morocco":"MA",
    "Mozambique":"MZ",
    "Namibia":"NA",
    "Nauru":"NR",
    "Nepal":"NP",
    "Netherlands":"NL",
    "New Zealand":"NZ",
    "Nicaragua":"NI",
    "Niger":"NE",
    "Nigeria":"NG",
    "Nieu":"NU",
    "Norway":"NO",
    "Oman":"OM",
    "Pakistan":"PK",
    "Palau":"PW",
    "Panama":"PA",
    "Papua New Guinea":"PG",
    "Paraguay":"PY",
    "Peru":"PE",
    "Philippines":"PH",
    "Poland":"PL",
    "Portugal":"PT",
    "Qatar":"QA",
    "Republic of Korea":"KR",
    "Republic of Moldova":"MD",
    "Romania":"RO",
    "Russian Federation":"RU",
    "Rwanda":"RW",
    "Saint Kitts and Nevis":"KN",
    "Saint Lucia":"LC",
    "Saint Vincent and the Grenadines":"VC",
    "Samoa":"WS",
    "San Marino":"SM",
    "Sao Tome and Principe":"ST",
    "Saudi Arabia":"SA",
    "Senegal":"SN",
    "Serbia and Montenegro":"CS",
    "Seychelles":"SC",
    "Sierra Leone":"SL",
    "Singapore":"SG",
    "Slovakia":"SK",
    "Slovenia":"SI",
    "Solomon Islands":"SB",
    "Somalia":"SO",
    "South Africa":"ZA",
    "Spain":"ES",
    "Sri Lanka":"LK",
    "Swaziland":"SZ",
    "Tajikistan":"TJ",
    "Thailand":"TH",
    "The former Yugoslav Republic of Macedonia":"MK",
    "Togo":"TG",
    "Tonga":"TO",
    "Trinidad and Tobago":"TT",
    "Tunisia":"TN",
    "Turkey":"TR",
    "Turkmenistan":"TM",
    "Tuvalu":"TV",
    "Uganda":"UG",
    "Ukraine":"UA",
    "United Arab Emirates":"AE",
    "United Kingdom":"GB",
    "United States of America":"US",
    "Uruguay":"UY",
    "Uzbekistan":"UZ",
    "Vanuatu":"VU",
    "Venezuela (Bolivarian Republic of)":"VE",
    "Viet Nam":"VN",
    "Yemen":"YE",
    "Zambia":"ZM",
    "Zimbabwe":"ZW"
}
